m = 5;
L = 256;
fs = 64;
fm = 1;
ts = 0:1/fs: 2 * 1/fm;
samples = Sampler(fm,fs);
quantized_samples = Quantizer(1, samples, L, m);
disp(samples);
disp(quantized_samples);
stairs(ts,quantized_samples);