mp = 5;
L = 8;
fs = 16;
fm = 1;
ts = 0:1/fs: 2 * 1/fm;
samples = Sampler(fm,fs);
quantized_samples = Quantizer(1, samples, L, mp);
% disp(samples);
% disp(quantized_samples);
stairs(ts,quantized_samples);
encoded_msg = Encoder(1, quantized_samples, mp, L, fs);
received_quantized = Decoder(1, encoded_msg,mp,L);
stairs(ts,received_quantized);